### ISSUE TITLE
Bug: incorrect callout type

### ISSUE THREAD

**Issue by gapmiss** [escwxyz/remark-obsidian-callout#20]
I discovered an incorrect Obsidian callout type.

https://github.com/escwxyz/remark-obsidian-callout/blob/59d1ba7bfb6e432fd31b1b662bce0a70e7eb036d/src/index.ts#L146

`cautions` should be singular `caution`

Thank you

**Comment by escwxyz** [comment]
> I discovered an incorrect Obsidian callout type.
> 
> https://github.com/escwxyz/remark-obsidian-callout/blob/59d1ba7bfb6e432fd31b1b662bce0a70e7eb036d/src/index.ts#L146
> 
> `cautions` should be singular `caution`
> 
> Thank you

You're right. Thanks for pointing out.

I would make patches when I get time this week, including some updates of the deps.

**Comment by escwxyz** [comment]
Or you can simply open a PR if you are urgent and willing to.

I'm kinda tired of the package managers and trying to switch to bun as my dev tooling for TS projects. But there are still some issues again to be addressed...
