### ISSUE TITLE
Getting ERR_MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by mj-meyer** [escwxyz/remark-obsidian-callout#45]
After adding to my Astro project, I get the following:

```zsh
[vite] Error when evaluating SSR module ..(filepathOmitted)/astro.config.mjs: failed to import "remark-obsidian-callout"
|- Error [ERR_MODULE_NOT_FOUND]: Cannot find module '..(filepathOmitted)/node_modules/.pnpm/remark-obsidian-callout@1.4.0/node_modules/remark-obsidian-callout/dist/icons' imported from ..(filepathOmitted)/node_modules/.pnpm/remark-obsidian-callout@1.4.0/node_modules/remark-obsidian-callout/dist/index.js
```

## Solution
I changed the icons import to have the `.js` extension [at line 19 here](https://github.com/escwxyz/remark-obsidian-callout/blob/aa3bba0e007bdb792e10d9983bda01c2bfb06820/src/index.ts#L19).

That seems to solve the errors around the icons file.

After that, I got an additional error around `mdast-util-to-string`
```zsh
[vite] Error when evaluating SSR module /src/utils/remark-reading-time.mjs: failed to import "mdast-util-to-string"
|- Error: Cannot find module 'mdast-util-to-string' imported from...
```

If you `pnpm add mdast-util-to-string` to the astro project, then it seems to resolve the issue. But I've noticed this on other remark plugins as well. Not sure if you want to add that to the docs... or if moving the dependency to the project instead of devDependency will fix this.

## Evironment:
pnpm: `8.15.5`
node: `22.9.0`
astro: `4.14.5`
remark-obsidian-callout: `1.4.0`

## Replication
I tried this on a fresh install using this theme:
`pnpm dlx create-astro --template kirontoo/astro-theme-cody`

That isolates the `.js` extension issue, as `mdast-util-to-string` was already to the package.json of that template.

**Comment by escwxyz** [comment]
Thanks for raising the issue.

I will check it myself when got time.

**Comment by escwxyz** [comment]
I have issue creating a minimal astro project right now because of the CLI failed to support socks5 proxy.

I will get back to this later

**Comment by escwxyz** [comment]
You're right. By looking at the code, we do miss this `mdast-util-to-string`.

I will fix this and release a new version.

**Comment by TotallyInformation** [comment]
v1.5.0 does not fix this issue.

**Comment by TotallyInformation** [comment]
There is a working version here: https://github.com/TotallyInformation/remark-obsidian-callout-fixed

**Comment by escwxyz** [comment]
> There is a working version here: https://github.com/TotallyInformation/remark-obsidian-callout-fixed

Thanks. I forgot that. 

Will publish a new release to fix it.

**Comment by escwxyz** [comment]
Shall be fixed now via https://github.com/escwxyz/remark-obsidian-callout/commit/cf9b5a39fe39e0f97a5bd50d8d89b5e580faa616
